export const discData = [
        
    { id:2, manuf:"Viking Discs", type:4, mold:"Warrior", plastic:"Armour", weight:"171g", color:"Keltainen", mint:"9", info:"", image:"vikwar-1.jpg;vikwar-2.jpg", status:"Vaihtari" },
    { id:4, manuf:"Viking Discs", type:2, mold:"Knife", plastic:"Storm", weight:"174g", color:"Punainen", mint:"9", info:"", image:";", status:"Muu" },
    { id:8, manuf:"Discraft", type:5, mold:"Drone", plastic:"BigZ", weight:"176g", color:"Oranssi", mint:"9+", info:"", image:"disdro-1.jpg;disdro-2.jpg", status:"Vaihtari" },
    { id:12, manuf:"Westside Discs", type:"5", mold:"Laulaja", plastic:"VIP", weight:"176g", color:"Punainen", mint:"9+", info:"", image:"weslau-1.jpg;weslau-2.jpg", status:"Vaihtari" },
    { id:14, manuf:"Innova", type:9, mold:"Firebird", plastic:"Gstar", weight:"167g", color:"Violetti", mint:"8+", info:"", image:"innfir-1.jpg;innfir-2.jpg", status:"Vaihtari" },
    { id:16, manuf:"Innova", type:9, mold:"Firebird", plastic:"Champion", weight:"167g", color:"Vaaleanpunainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:18, manuf:"Innova", type:9, mold:"Thunderbird", plastic:"Champion", weight:"168g", color:"Keltavihreä", mint:"8", info:"", image:"innthu-1.jpg;innthu-2.jpg", status:"Muu" },
    { id:20, manuf:"Latitude64", type:10, mold:"Musket", plastic:"Opto", weight:"175g", color:"Punainen", mint:"8", info:"Siisti pieni tussi rimmissä", image:"latmus-1.jpg;latmus-2.jpg", status:"Vaihtari" },
    { id:22, manuf:"Latitude64", type:9, mold:"Bryce", plastic:"Opto-G", weight:"174g", color:"Keltainen/Valkoinen", mint:"9+", info:"Kaksoismoldi", image:"latbry-1.jpg;latbry-2.jpg", status:"Vaihtari" },
    { id:24, manuf:"Westside Discs", type:14, mold:"Pohjolan isäntä", plastic:"Tournament", weight:"175g", color:"Keltavihreä", mint:"8+", info:"", image:"wespoh-1.jpg;wespoh-2.jpg", status:"Vaihtari" },
    { id:26, manuf:"Westside Discs", type:3, mold:"Tuonelan joutsen 2", plastic:"BT Soft", weight:"174g", color:"Vaaleanpunainen", mint:"8+", info:"", image:"westuo-1.jpg;westuo-2.jpg", status:"Vaihtari" },
    { id:28, manuf:"Innova", type:4, mold:"Roc", plastic:"DX", weight:"180g", color:"Vaaleanpunainen", mint:"9+", info:"", image:"", status:"Vaihtari" },
    { id:30, manuf:"Innova", type:5, mold:"RocX3", plastic:"Champion", weight:"168g", color:"Vaaleanpunainen", mint:"8+", info:"", image:"innrx3-1.jpg;innrx3-2.jpg", status:"Vaihtari" },
    { id:32, manuf:"Innova", type:4, mold:"Roc", plastic:"DX", weight:"180g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Bägi" },
    { id:33, manuf:"Innova", type:4, mold:"Roc", plastic:"KC Pro", weight:"180g", color:"Violetti", mint:"9+", info:"", image:"", status:"Muu" },
    { id:34, manuf:"Discraft", type:5, mold:"Hornet", plastic:"Z", weight:"175g", color:"Sininen", mint:"8", info:"", image:"", status:"Bägi" },
    { id:36, manuf:"Discraft", type:5, mold:"Hornet", plastic:"Z", weight:"175g", color:"Sininen", mint:"9+", info:"", image:"", status:"Bägi" },
    { id:38, manuf:"Discraft", type:5, mold:"Hornet", plastic:"Z", weight:"175g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Bägi" },
    { id:40, manuf:"Innova", type:2, mold:"Rhyno", plastic:"Champion", weight:"175g", color:"Sininen", mint:"8+", info:"", image:"", status:"Bägi" },
    { id:42, manuf:"Innova", type:2, mold:"Rhyno", plastic:"DX", weight:"175g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:44, manuf:"Innova", type:2, mold:"Rhyno", plastic:"DX", weight:"175g", color:"Violetti", mint:"9+", info:"", image:"innrhy-1.jpg;innrhy-2.jpg", status:"Muu" },
    { id:46, manuf:"Innova", type:3, mold:"Dart", plastic:"DX", weight:"175g", color:"Vaaleanpunainen", mint:"8", info:"", image:"", status:"Bägi" },
    { id:48, manuf:"Innova", type:12, mold:"Tern", plastic:"Champion", weight:"167g", color:"Sininen", mint:"8", info:"", image:"", status:"Bägi" },
    { id:50, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Gstar", weight:"171g", color:"Vihreä", mint:"8+", info:"", image:"", status:"Muu" },
    { id:52, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Champion", weight:"171g", color:"Vihreä", mint:"9-", info:"", image:"innchdes3-1.jpg;innchdes3-2.jpg", status:"Vaihtari" },
    { id:54, manuf:"Innova", type:2, mold:"Aviar-X", plastic:"JK Pro", weight:"175g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:56, manuf:"Innova", type:2, mold:"Aviar Driver", plastic:"Gstar", weight:"175g", color:"Punainen", mint:"9", info:"", image:"innavd-1.jpg;innavd-2.jpg", status:"Vaihtari" },
    { id:58, manuf:"Innova", type:2, mold:"Aviar P&A", plastic:"Champion", weight:"175g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:60, manuf:"Innova", type:2, mold:"Nova", plastic:"XT", weight:"172g", color:"Violetti/Keltainen", mint:"8+", info:"Kaksoismoldi, Misprint", image:"", status:"Muu" },
    { id:62, manuf:"Innova", type:3, mold:"Pig", plastic:"R-Pro", weight:"175g", color:"Violetti", mint:"8+", info:"", image:"", status:"Muu" },
    { id:64, manuf:"Innova", type:3, mold:"Colt", plastic:"XT", weight:"175g", color:"Violetti", mint:"8+", info:"", image:"", status:"Muu" },
    { id:66, manuf:"Innova", type:3, mold:"Colt", plastic:"Gstar", weight:"175g", color:"Violetti", mint:"9-", info:"", image:"inncol-1.jpg;inncol-2.jpg", status:"Vaihtari" },
    { id:68, manuf:"Innova", type:3, mold:"Colt", plastic:"DX", weight:"175g", color:"Violetti", mint:"8+", info:"", image:"", status:"Muu" },
    { id:70, manuf:"Innova", type:3, mold:"Colt", plastic:"Gstar", weight:"175g", color:"Oranssi", mint:"9-", info:"", image:"", status:"Muu" },
    { id:72, manuf:"Discmania", type:3, mold:"P3X", plastic:"S-line", weight:"175g", color:"Valkoinen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:74, manuf:"Westside Discs", type:3, mold:"Tuonelan joutsen 2", plastic:"BT soft", weight:"175g", color:"Vaaleanpunainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:78, manuf:"Discraft", type:3, mold:"Fierce", plastic:"Prototype putter blend", weight:"175g", color:"Vaaleanpunainen", mint:"9+", info:"Paige Pierce Prototype", image:"", status:"Muu" },
    { id:71, manuf:"Latitude64", type:2, mold:"Keystone", plastic:"Zero Medium Splatter", weight:"175g", color:"Vaaleanpunainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:73, manuf:"Innova", type:3, mold:"Stud", plastic:"DX", weight:"168g", color:"Valkoinen", mint:"7", info:"", image:"", status:"Muu" },
    { id:75, manuf:"Westside Discs", type:3, mold:"Kilpi", plastic:"BT Soft", weight:"175g", color:"Punainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:77, manuf:"Westside Discs", type:3, mold:"Crown", plastic:"BT Soft", weight:"175g", color:"Sininen", mint:"8", info:"", image:"", status:"Muu" },
    { id:80, manuf:"Latitude64", type:2, mold:"Gauntlet", plastic:"Zero Soft", weight:"175g", color:"Valkoinen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:82, manuf:"Latitude64", type:3, mold:"Pure", plastic:"Zero Soft", weight:"175g", color:"Musta", mint:"9", info:"", image:"", status:"Muu" },
    { id:84, manuf:"Westside Discs", type:3, mold:"Maiden", plastic:"BT Soft", weight:"175g", color:"Keltainen", mint:"9", info:"", image:"", status:"Muu" },
    { id:86, manuf:"Dynamic Discs", type:3, mold:"Deputy", plastic:"Classic Blend Burst", weight:"175g", color:"Ruskea", mint:"8+", info:"", image:"", status:"Muu" },
    { id:88, manuf:"Innova", type:4, mold:"Rat", plastic:"Star", weight:"171g", color:"Vaaleanpunainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:90, manuf:"Innova", type:3, mold:"Mirage", plastic:"Star", weight:"175g", color:"Vaaleanpunainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:92, manuf:"Innova", type:5, mold:"Caiman", plastic:"Star", weight:"175g", color:"Vihreä", mint:"8+", info:"", image:"", status:"Muu" },
    { id:94, manuf:"Discmania", type:10, mold:"PD", plastic:"C-line", weight:"175g", color:"Vihreä", mint:"8+", info:"", image:"", status:"Muu" },
    { id:96, manuf:"Innova", type:7, mold:"Teebird", plastic:"Champion", weight:"175g", color:"Keltavihreä", mint:"8+", info:"", image:"", status:"Muu" },
    { id:98, manuf:"Discmania", type:7, mold:"FD", plastic:"C-line", weight:"175g", color:"Vaaleanpunainen", mint:"9-", info:"", image:"", status:"Muu" },
    { id:100, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Gstar", weight:"166g", color:"Oranssi", mint:"8", info:"", image:"inngsdes-1.jpg;inngsdes-2.jpg", status:"Vaihtari" },
    { id:102, manuf:"Innova", type:11, mold:"Wraith", plastic:"Gstar", weight:"171g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:104, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Gstar", weight:"175g", color:"Violetti", mint:"9+", info:"", image:"", status:"Muu" },
    { id:106, manuf:"Innova", type:5, mold:"Panther", plastic:"Champion", weight:"175g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:108, manuf:"Innova", type:5, mold:"Panther", plastic:"Champion", weight:"175g", color:"Keltavihreä", mint:"8", info:"", image:"", status:"Muu" },
    { id:112, manuf:"Innova", type:11, mold:"Wraith", plastic:"Pro", weight:"175g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:114, manuf:"Innova", type:7, mold:"Teebird", plastic:"DX", weight:"175g", color:"Vaaleanpunainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:116, manuf:"Innova", type:6, mold:"Leopard", plastic:"Star", weight:"175g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:118, manuf:"Innova", type:6, mold:"Leopard", plastic:"Gstar", weight:"175g", color:"Oranssi", mint:"9+", info:"", image:"", status:"Muu" },
    { id:120, manuf:"Innova", type:8, mold:"Teebird3", plastic:"Metal flake", weight:"175g", color:"Vaaleanpunainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:122, manuf:"Innova", type:7, mold:"Teebird", plastic:"Champion", weight:"175g", color:"Violetti", mint:"9+", info:"", image:"", status:"Muu" },
    { id:124, manuf:"Innova", type:7, mold:"Teebird", plastic:"Star", weight:"175g", color:"Sininen", mint:"9+", info:"Avery Jenkins", image:"", status:"Muu" },
    { id:126, manuf:"Innova", type:9, mold:"Thunderbird", plastic:"Pro", weight:"175g", color:"Violetti", mint:"8", info:"", image:"", status:"Muu" },
    { id:128, manuf:"Innova", type:9, mold:"Thunderbird", plastic:"Pro", weight:"175g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Muu" },
    { id:130, manuf:"Innova", type:9, mold:"Valkyrie", plastic:"Star", weight:"175g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:132, manuf:"Innova", type:7, mold:"Banshee", plastic:"Champion", weight:"175g", color:"Punainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:134, manuf:"Innova", type:9, mold:"Valkyrie", plastic:"Star", weight:"170g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:136, manuf:"Discmania", type:10, mold:"PD", plastic:"D-line", weight:"175g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:138, manuf:"Innova", type:10, mold:"Beast", plastic:"Champion", weight:"175g", color:"Monivärinen", mint:"8", info:"", image:"", status:"Muu" },
    { id:140, manuf:"Innova", type:10, mold:"Beast", plastic:"Star", weight:"175g", color:"Monivärinen", mint:"8+", info:"Swirly", image:"", status:"Muu" },
    { id:142, manuf:"Innova", type:10, mold:"Beast", plastic:"Pro", weight:"175g", color:"Oranssi", mint:"8", info:"", image:"", status:"Muu" },
    { id:144, manuf:"Innova", type:8, mold:"Teebird3", plastic:"Gstar", weight:"175g", color:"Punainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:146, manuf:"Innova", type:8, mold:"Teebird3", plastic:"Star", weight:"175g", color:"Sininen", mint:"8", info:"", image:"", status:"Muu" },
    { id:152, manuf:"Discmania", type:5, mold:"MD4", plastic:"C-line", weight:"179g", color:"Punainen", mint:"9", info:"", image:"", status:"Muu" },
    { id:154, manuf:"Discmania", type:5, mold:"MD3", plastic:"G-line", weight:"180g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:156, manuf:"Discmania", type:5, mold:"MD5", plastic:"C-line", weight:"172g", color:"Punainen", mint:"9-", info:"", image:"", status:"Muu" },
    { id:158, manuf:"Innova", type:5, mold:"Shark3", plastic:"Champion", weight:"173g", color:"Ruskea", mint:"9", info:"", image:"", status:"Muu" },
    { id:160, manuf:"Innova", type:2, mold:"Aviar P&A", plastic:"DX", weight:"175g", color:"Vaaleansininen", mint:"7", info:"", image:"", status:"Muu" },
    { id:162, manuf:"Discmania", type:2, mold:"P1X", plastic:"P-line", weight:"175g", color:"Valkoinen", mint:"7", info:"", image:"", status:"Muu" },
    { id:164, manuf:"Innova", type:3, mold:"Mirage", plastic:"DX", weight:"175g", color:"Valkoinen", mint:"7", info:"", image:"", status:"Muu" },
    { id:166, manuf:"Innova", type:2, mold:"Aviar P&A", plastic:"DX", weight:"111g", color:"Sininen", mint:"9", info:"", image:"", status:"Muu" },
    { id:168, manuf:"Innova", type:1, mold:"Birdie", plastic:"DX", weight:"177g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:170, manuf:"Innova", type:1, mold:"Polecat", plastic:"DX", weight:"173g", color:"Valkoinen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:172, manuf:"Innova", type:2, mold:"Aviar Classic", plastic:"DX", weight:"174g", color:"Vaaleanpunainen", mint:"7", info:"", image:"", status:"Muu" },
    { id:174, manuf:"Innova", type:3, mold:"Pig", plastic:"R-Pro", weight:"175g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:176, manuf:"Innova", type:12, mold:"Tern", plastic:"Star", weight:"169g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:178, manuf:"Innova", type:11, mold:"Mamba", plastic:"Star", weight:"171g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:180, manuf:"Innova", type:12, mold:"Tern", plastic:"Champion", weight:"175g", color:"Vaaleanruskea", mint:"8+", info:"", image:"", status:"Muu" },
    { id:182, manuf:"Discmania", type:11, mold:"CD3", plastic:"S-line", weight:"175g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:184, manuf:"Innova", type:13, mold:"Daedalus", plastic:"Star", weight:"169g", color:"Vaaleanvihreä", mint:"7", info:"", image:"", status:"Muu" },
    { id:186, manuf:"Discmania", type:11, mold:"DD", plastic:"S-line", weight:"174g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:188, manuf:"Innova", type:11, mold:"Wraith", plastic:"Champion", weight:"175g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:190, manuf:"Innova", type:11, mold:"Mystere", plastic:"Star", weight:"171g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Muu" },
    { id:192, manuf:"Innova", type:11, mold:"Wraith", plastic:"Gstar", weight:"171g", color:"Vihreä", mint:"9+", info:"", image:"", status:"Muu" },
    { id:194, manuf:"Innova", type:11, mold:"Archon", plastic:"Star", weight:"171g", color:"Valkoinen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:196, manuf:"Innova", type:11, mold:"Archon", plastic:"Champion", weight:"175g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:198, manuf:"Innova", type:11, mold:"Mystere", plastic:"Champion", weight:"175g", color:"Viininpunainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:200, manuf:"Innova", type:12, mold:"Destroyer", plastic:"DX", weight:"175g", color:"Sininen", mint:"8", info:"", image:"", status:"Muu" },
    { id:202, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Gstar", weight:"171g", color:"Keltainen", mint:"9", info:"", image:"", status:"Muu" },
    { id:204, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Pro", weight:"167g", color:"Vaaleanpunainen", mint:"6", info:"", image:"", status:"Muu" },
    { id:206, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Champion", weight:"167g", color:"Violetti", mint:"8+", info:"", image:"innchdes1-1.jpg;innchdes1-2.jpg", status:"Vaihtari" },
    { id:208, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Champion", weight:"170g", color:"Punainen", mint:"9", info:"", image:"innchdes2-1.jpg;innchdes2-2.jpg", status:"Vaihtari" },
    { id:210, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Champion", weight:"175g", color:"Sininen", mint:"9", info:"", image:"innchdes4-1.jpg;innchdes4-2.jpg", status:"Vaihtari" },
    { id:212, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Star", weight:"166g", color:"Punainen", mint:"8+", info:"", image:"innstdes1-1.jpg;innstdes1-2.jpg", status:"Vaihtari" },
    { id:214, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Star", weight:"168g", color:"Oranssi", mint:"8+", info:"", image:"innstdes2-1.jpg;innstdes2-2.jpg", status:"Vaihtari" },
    { id:216, manuf:"Innova", type:12, mold:"Destroyer", plastic:"Star", weight:"171g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:218, manuf:"Prodigy", type:3, mold:"PA4", plastic:"400", weight:"175g", color:"Musta", mint:"9-", info:"", image:"", status:"Muu" },
    { id:220, manuf:"Prodigy", type:3.5, mold:"A4", plastic:"300", weight:"175g", color:"Valkoinen", mint:"8-", info:"", image:"", status:"Muu" },
    { id:222, manuf:"Prodigy", type:3, mold:"PA3", plastic:"300", weight:"173g", color:"Valkoinen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:224, manuf:"Prodigy", type:3.5, mold:"A3", plastic:"400", weight:"173g", color:"Musta", mint:"8", info:"", image:"", status:"Muu" },
    { id:226, manuf:"Prodigy", type:5, mold:"M3", plastic:"300s", weight:"173g", color:"Vaalea", mint:"8", info:"", image:"", status:"Muu" },
    { id:228, manuf:"Prodigy", type:3, mold:"PA4", plastic:"750", weight:"171g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:230, manuf:"Prodigy", type:3.5, mold:"A4", plastic:"400g", weight:"171g", color:"Harmaa", mint:"8+", info:"", image:"", status:"Muu" },
    { id:232, manuf:"Prodigy", type:3.5, mold:"A3", plastic:"300", weight:"173g", color:"Vaaleanpunainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:234, manuf:"Prodigy", type:5, mold:"M5", plastic:"400g", weight:"177g", color:"Vaaleanpunainen", mint:"9+", info:"", image:"prom5-1.jpg;prom5-2.jpg", status:"Vaihtari" },
    { id:236, manuf:"Prodigy", type:3.5, mold:"A2", plastic:"400", weight:"172g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Muu" },
    { id:238, manuf:"Prodigy", type:10, mold:"H2V2", plastic:"400", weight:"175g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:240, manuf:"Prodigy", type:13, mold:"D3", plastic:"400g", weight:"173g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:242, manuf:"Prodigy", type:12, mold:"D4", plastic:"400", weight:"174g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:244, manuf:"Prodigy", type:7, mold:"F1", plastic:"400", weight:"172g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:246, manuf:"Prodigy", type:3.5, mold:"A3", plastic:"400", weight:"174g", color:"Vihreä", mint:"8", info:"", image:"", status:"Muu" },
    { id:248, manuf:"Prodigy", type:5, mold:"M2", plastic:"400", weight:"177g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:250, manuf:"Prodigy", type:9, mold:"H2", plastic:"400g", weight:"173g", color:"Oranssi", mint:"8+", info:"", image:"proh2-1.jpg;proh2-2.jpg", status:"Vaihtari" },
    { id:252, manuf:"Prodigy", type:10, mold:"H1V2", plastic:"400", weight:"173g", color:"Vihreä", mint:"9", info:"", image:"", status:"Muu" },
    { id:254, manuf:"Prodigy", type:9, mold:"H3", plastic:"400g", weight:"172g", color:"Vihreä", mint:"8+", info:"", image:"proh3-1.jpg;proh3-2.jpg", status:"Vaihtari" },
    { id:256, manuf:"Prodigy", type:10, mold:"H3V2", plastic:"400", weight:"172g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:258, manuf:"Latitude64", type:9, mold:"Culverin", plastic:"Gold", weight:"174g", color:"Punainen", mint:"8", info:"", image:"latcul-1.jpg;latcul-2.jpg", status:"Vaihtari" },
    { id:260, manuf:"Latitude64", type:9, mold:"Culverin", plastic:"Opto", weight:"173g", color:"Violetti", mint:"9+", info:"", image:"", status:"Muu" },
    { id:262, manuf:"Latitude64", type:11, mold:"Flow", plastic:"Opto", weight:"172g", color:"Vaaleanpunainen", mint:"9", info:"", image:"", status:"Muu" },
    { id:264, manuf:"Westside discs", type:10, mold:"Tuonelan lautturi", plastic:"VIP", weight:"171g", color:"Punainen", mint:"7+", info:"", image:"", status:"Muu" },
    { id:266, manuf:"Latitude64", type:13, mold:"Bolt", plastic:"Opto", weight:"167g", color:"Sininen", mint:"6", info:"", image:"", status:"Muu" },
    { id:268, manuf:"Westside discs", type:12, mold:"Sword", plastic:"VIP", weight:"173g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:270, manuf:"Westside discs", type:14, mold:"World", plastic:"Tournament", weight:"171g", color:"Sininen", mint:"9-", info:"", image:"", status:"Muu" },
    { id:272, manuf:"Westside discs", type:10, mold:"Tuonelan lautturi", plastic:"Tournament", weight:"173g", color:"Keltainen", mint:"8", info:"Rumat tussit pohjassa", image:"", status:"Muu" },
    { id:274, manuf:"Westside discs", type:10, mold:"Tuonelan lautturi", plastic:"BT origio", weight:"175g", color:"Vaaleanpunainen", mint:"8", info:"", image:"", status:"Muu" },
    { id:276, manuf:"Westside discs", type:13, mold:"Tietäjä", plastic:"VIP", weight:"173g", color:"Sininen", mint:"8", info:"", image:"", status:"Muu" },
    { id:278, manuf:"Westside discs", type:14, mold:"Pohjolan isäntä", plastic:"VIP", weight:"172g", color:"Violetti", mint:"7", info:"Rumat tussit", image:"", status:"Muu" },
    { id:280, manuf:"Westside discs", type:14, mold:"Catapult", plastic:"Tournament", weight:"174g", color:"Vaalea", mint:"8+", info:"", image:"", status:"Muu" },
    { id:282, manuf:"Westside discs", type:7, mold:"Manala", plastic:"VIP", weight:"176g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:284, manuf:"Latitude64", type:9, mold:"Pioneer", plastic:"Opto", weight:"173g", color:"Punainen", mint:"9", info:"", image:"", status:"Muu" },
    { id:286, manuf:"Latitude64", type:9, mold:"Saint", plastic:"Opto", weight:"174g", color:"Oranssi", mint:"9+", info:"", image:"", status:"Muu" },
    { id:288, manuf:"Westside discs", type:3, mold:"Tuonelan joutsen 1", plastic:"Mega Soft", weight:"175g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:290, manuf:"Latitude64", type:2, mold:"Dagger", plastic:"Zero Medium", weight:"173g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:292, manuf:"Latitude64", type:3.5, mold:"Spike", plastic:"Zero Soft Burst", weight:"173g", color:"Vaaleansininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:294, manuf:"Westside discs", type:3.5, mold:"Kannel", plastic:"VIP", weight:"174g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:296, manuf:"Latitude64", type:2, mold:"Macana", plastic:"Zero Soft", weight:"173g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:298, manuf:"Latitude64", type:2, mold:"Mercy", plastic:"Zero Soft", weight:"175g", color:"Punainen", mint:"7+", info:"", image:"", status:"Muu" },
    { id:300, manuf:"Westside discs", type:4, mold:"Anvil", plastic:"VIP", weight:"175g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:302, manuf:"Dynamic discs", type:5, mold:"Verdict", plastic:"Lucid", weight:"177g", color:"Vaalea", mint:"9+", info:"", image:"", status:"Muu" },
    { id:304, manuf:"Dynamic discs", type:2, mold:"Guard", plastic:"Classic", weight:"173g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:306, manuf:"Latitude64", type:2, mold:"Mercy", plastic:"Zero Hard", weight:"176g", color:"Sininen", mint:"8+", info:"", image:"latmer-1.jpg;latmer-2.jpg", status:"Vaihtari" },
    { id:308, manuf:"Latitude64", type:5, mold:"Anchor", plastic:"Opto", weight:"169g", color:"Oranssi", mint:"9+", info:"", image:"latanc-1.jpg;latanc-2.jpg", status:"Vaihtari" },
    { id:310, manuf:"Dynamic discs", type:4, mold:"Suspect", plastic:"Lucid", weight:"173g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:312, manuf:"MVP", type:5, mold:"Deflector", plastic:"Neutron", weight:"174g", color:"Sininen/Musta", mint:"9+", info:"", image:"", status:"Muu" },
    { id:314, manuf:"Discraft", type:4, mold:"Meteor", plastic:"ESP", weight:"172g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Muu" },
    { id:318, manuf:"Viking discs", type:4, mold:"Loki", plastic:"Ground", weight:"171g", color:"Oranssi", mint:"9+", info:"", image:"viklok-1.jpg;viklok-2.jpg", status:"Vaihtari" },
    { id:320, manuf:"Viking discs", type:4, mold:"Axe", plastic:"Ground", weight:"170g", color:"Valkoinen", mint:"7-", info:"", image:"", status:"Muu" },
    { id:322, manuf:"Viking discs", type:4, mold:"Loki", plastic:"Armor", weight:"175g", color:"Valkoinen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:324, manuf:"Viking discs", type:4, mold:"Loki", plastic:"Ground", weight:"171g", color:"Oranssi", mint:"7-", info:"", image:"", status:"Muu" },
    { id:326, manuf:"Discraft", type:4, mold:"Meteor", plastic:"Z", weight:"172g", color:"Oranssi", mint:"8+", info:"", image:"", status:"Muu" },
    { id:328, manuf:"Viking discs", type:12, mold:"Valhalla", plastic:"Armor", weight:"171g", color:"Valkoinen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:330, manuf:"Viking discs", type:11, mold:"Ragnarök", plastic:"Ground", weight:"171g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:332, manuf:"Yikun discs", type:11, mold:"Jun", plastic:"Phoenix", weight:"176g", color:"Punainen", mint:"7", info:"", image:"", status:"Muu" },
    { id:334, manuf:"Kastaplast", type:6, mold:"Kaxe Z", plastic:"K1", weight:"175g", color:"Keltainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:336, manuf:"Viking discs", type:4, mold:"Warrior", plastic:"Storm", weight:"172g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:338, manuf:"Viking discs", type:4, mold:"Warrior", plastic:"Armor", weight:"175g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:340, manuf:"Prodiscus", type:3.5, mold:"Jokeri", plastic:"Basic", weight:"173g", color:"Punainen", mint:"8-", info:"", image:"", status:"Muu" },
    { id:342, manuf:"Viking discs", type:2, mold:"Rune", plastic:"Ground", weight:"171g", color:"Valkoinen", mint:"8-", info:"", image:"", status:"Muu" },
    { id:344, manuf:"Discraft", type:3.5, mold:"Zone", plastic:"D-Pro", weight:"172g", color:"Sininen", mint:"7", info:"", image:"", status:"Muu" },
    { id:346, manuf:"Discraft", type:3.5, mold:"Zone", plastic:"D-Pro", weight:"177g", color:"Vihreä", mint:"8+", info:"", image:"", status:"Muu" },
    { id:348, manuf:"Prodiscus", type:3.5, mold:"Jokeri", plastic:"Ultrium", weight:"174g", color:"Punainen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:350, manuf:"Viking discs", type:2, mold:"Rune", plastic:"Ground", weight:"171g", color:"Valkoinen", mint:"7", info:"", image:"", status:"Muu" },
    { id:352, manuf:"Viking discs", type:2, mold:"Knife", plastic:"Ground", weight:"171g", color:"Valkoinen", mint:"9-", info:"", image:"", status:"Muu" },
    { id:354, manuf:"Viking discs", type:2, mold:"Rune", plastic:"Armor", weight:"174g", color:"Punainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:356, manuf:"Yikun discs", type:3.5, mold:"Wings", plastic:"Phoenix", weight:"170g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Vesi" },
    { id:358, manuf:"Dynamic discs", type:4, mold:"Suspect", plastic:"Classic Blend", weight:"174g", color:"Violetti", mint:"6", info:"", image:"", status:"Vesi" },
    { id:362, manuf:"Yikun discs", type:4, mold:"Yao", plastic:"Phoenix", weight:"172g", color:"Sininen", mint:"8+", info:"", image:"", status:"Muu" },
    { id:366, manuf:"Yikun discs", type:3.5, mold:"Wings", plastic:"Phoenix", weight:"173g", color:"Keltainen", mint:"7", info:"", image:"", status:"Vesi" },
    { id:368, manuf:"Viking discs", type:4, mold:"Axe", plastic:"Storm", weight:"163g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Vesi" },
    { id:370, manuf:"Innova", type:7, mold:"Banshee", plastic:"DX", weight:"174g", color:"Oranssi", mint:"8", info:"", image:"", status:"Muu" },
    { id:372, manuf:"Innova", type:9, mold:"Valkyrie", plastic:"DX", weight:"174g", color:"Punainen", mint:"5", info:"", image:"", status:"Muu" },
    { id:374, manuf:"Innova", type:3, mold:"AviarX3", plastic:"Champion", weight:"175g", color:"Keltainen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:376, manuf:"Innova", type:11, mold:"Mamba", plastic:"Champion", weight:"175g", color:"Sininen", mint:"9+", info:"", image:"", status:"Muu" },
    { id:378, manuf:"Westside Discs", type:12, mold:"Vipunen", plastic:"BT", weight:"172g", color:"Punainen", mint:"7+", info:"", image:"", status:"Muu" },
    { id:380, manuf:"Discmania", type:4, mold:"Tactic", plastic:"Exo", weight:"174g", color:"Sininen", mint:"9", info:"", image:"", status:"Muu" },
    { id:382, manuf:"Latitude64", type:2, mold:"Sinus", plastic:"Zero soft", weight:"174g", color:"Valkoinen", mint:"9", info:"", image:"", status:"Muu" },
    
];

export const DISPLAY_MODE = 'ALL';
//export const DISPLAY_MODE = 'ONLY_TRADE_DISCS';

//export default discData;